import express from "express";
import mongoose from "mongoose"; // ✅ Make sure mongoose is imported
import Attendance from "../models/Attendance.js";
import User from "../models/User.js";

const router = express.Router();

// Manual attendance entry (check-in and check-out)
router.post("/manual-entry", async (req, res) => {
  try {
    const { email, date, checkInTime, checkOutTime, location, notes } =
      req.body;

    console.log("📝 Received attendance data:", {
      email,
      date,
      checkInTime,
      checkOutTime,
    });

    if (!email || !date || !checkInTime) {
      return res
        .status(400)
        .json({ error: "Email, date, and check-in time are required" });
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res
        .status(400)
        .json({ error: "Please enter a valid email address" });
    }

    // Validate date format (YYYY-MM-DD)
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    if (!dateRegex.test(date)) {
      return res
        .status(400)
        .json({ error: "Date must be in YYYY-MM-DD format" });
    }

    // Check if user exists with this email
    const user = await User.findOne({ email: email.toLowerCase() });
    if (!user) {
      return res
        .status(400)
        .json({ error: `No user found with email: ${email}` });
    }

    // ✅ Check if attendance already exists for this email and date
    const existingAttendance = await Attendance.findOne({
      email: email.toLowerCase(),
      date: date,
    });

    if (existingAttendance) {
      const existingTime = new Date(
        existingAttendance.checkIn.time
      ).toLocaleTimeString();
      return res.status(400).json({
        error: `Attendance already exists for ${email} on ${date}. Check-in time: ${existingTime}`,
      });
    }

    // Create check-in and check-out objects
    const checkIn = {
      time: new Date(`${date}T${checkInTime}`),
      location: location || "Office",
      notes: notes || "",
    };

    let checkOut = null;
    if (checkOutTime) {
      checkOut = {
        time: new Date(`${date}T${checkOutTime}`),
        location: location || "Office",
        notes: notes || "",
      };

      // Validate that check-out time is after check-in time
      if (checkOut.time <= checkIn.time) {
        return res
          .status(400)
          .json({ error: "Check-out time must be after check-in time" });
      }
    }

    // ✅ Create attendance with unique userId (automatically generated by model)
    const attendance = new Attendance({
      email: email.toLowerCase(),
      date,
      // userId is automatically generated by the model's default function
      checkIn,
      checkOut,
    });

    await attendance.save();

    console.log("✅ Attendance recorded successfully for:", email);

    res.status(201).json({
      message: "Attendance recorded successfully",
      attendance: attendance,
    });
  } catch (error) {
    console.error("❌ Manual attendance entry error:", error);

    // Handle duplicate key error (unique constraint violation)
    if (error.code === 11000) {
      return res.status(400).json({
        error: "Attendance record already exists for this email and date",
      });
    }

    res.status(500).json({ error: error.message });
  }
});

// Check-out only (update existing record)
router.post("/checkout-only", async (req, res) => {
  try {
    const { email, checkOutTime, location, notes } = req.body;

    console.log("🕒 Check-out request for:", { email, checkOutTime });

    if (!email || !checkOutTime) {
      return res
        .status(400)
        .json({ error: "Email and check-out time are required" });
    }

    const today = new Date().toISOString().split("T")[0];

    // Find today's attendance record for this specific email
    const attendance = await Attendance.findOne({
      email: email.toLowerCase(),
      date: today,
    });

    if (!attendance) {
      return res.status(400).json({
        error: `No check-in found for ${email} today. Please check in first.`,
      });
    }

    if (attendance.checkOut && attendance.checkOut.time) {
      const checkoutTime = new Date(
        attendance.checkOut.time
      ).toLocaleTimeString();
      return res.status(400).json({
        error: `${email} is already checked out. Check-out time: ${checkoutTime}`,
      });
    }

    // Update check-out time
    attendance.checkOut = {
      time: new Date(`${today}T${checkOutTime}`),
      location: location || "Office",
      notes: notes || "",
    };

    // Validate that check-out time is after check-in time
    if (attendance.checkOut.time <= attendance.checkIn.time) {
      return res
        .status(400)
        .json({ error: "Check-out time must be after check-in time" });
    }

    await attendance.save();

    console.log("✅ Check-out recorded successfully for:", email);

    res.json({
      message: "Check-out recorded successfully",
      attendance: attendance,
    });
  } catch (error) {
    console.error("❌ Check-out only error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Get today's attendance for an email
router.get("/today/:email", async (req, res) => {
  try {
    const { email } = req.params;
    const today = new Date().toISOString().split("T")[0];

    const attendance = await Attendance.findOne({
      email: email.toLowerCase(),
      date: today,
    });

    res.json(attendance);
  } catch (error) {
    // Return null instead of error if no record found
    res.json(null);
  }
});

// Get attendance by email and date range
router.get("/", async (req, res) => {
  try {
    const { startDate, endDate, email } = req.query;

    let query = {};

    if (startDate && endDate) {
      query.date = {
        $gte: startDate,
        $lte: endDate,
      };
    }

    if (email) {
      query.email = email.toLowerCase();
    }

    const attendance = await Attendance.find(query).sort({
      date: -1,
      "checkIn.time": -1,
    });

    res.json(attendance);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get today's attendance for an email
router.get("/today/:email", async (req, res) => {
  try {
    const { email } = req.params;
    const today = new Date().toISOString().split("T")[0];

    const attendance = await Attendance.findOne({
      email: email.toLowerCase(),
      date: today,
    });

    res.json(attendance);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get user's attendance summary by email
router.get("/summary/:email", async (req, res) => {
  try {
    const { email } = req.params;
    const { month, year } = req.query;

    let startDate, endDate;

    if (month && year) {
      startDate = `${year}-${month.toString().padStart(2, "0")}-01`;
      const lastDay = new Date(year, month, 0).getDate();
      endDate = `${year}-${month.toString().padStart(2, "0")}-${lastDay}`;
    } else {
      // Current month
      const now = new Date();
      const currentYear = now.getFullYear();
      const currentMonth = now.getMonth() + 1;
      startDate = `${currentYear}-${currentMonth
        .toString()
        .padStart(2, "0")}-01`;
      const lastDay = new Date(currentYear, currentMonth, 0).getDate();
      endDate = `${currentYear}-${currentMonth
        .toString()
        .padStart(2, "0")}-${lastDay}`;
    }

    const attendance = await Attendance.find({
      email: email.toLowerCase(),
      date: { $gte: startDate, $lte: endDate },
    }).sort({ date: -1 });

    const summary = {
      totalDays: attendance.length,
      present: attendance.filter((a) => a.status === "present").length,
      halfDays: attendance.filter((a) => a.status === "half-day").length,
      totalHours: attendance.reduce((sum, a) => sum + a.totalHours, 0),
      totalOvertime: attendance.reduce((sum, a) => sum + a.overtime, 0),
    };

    res.json({ summary, attendance });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Delete attendance record
router.delete("/:id", async (req, res) => {
  try {
    const { id } = req.params;
    await Attendance.findByIdAndDelete(id);
    res.json({ message: "Attendance record deleted successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
